apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-ui-anyhost
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
       backend:
          service:
            name: ui
            port:
              number: 80
