apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-ui-anyhost
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: retail-ui
            port:
              number: 80

